### ISSUE TITLE
Add previous/Next buttons top of page

### ISSUE THREAD

**Issue by Jblack017** [learn-co-curriculum/phase-0-intro-to-js-2-arrays#1]
For better ease of navigation

**Comment by lizbur10** [comment]
Hi there! I'm assuming that this suggestion is for all lessons/labs and not just this one, so I'm going to close this issue. For this type of feedback (i.e., something other than an error or issue with a specific lab or lesson), you might want to use the feedback link that's at the bottom of each Canvas lesson/lab instead.

Thanks for the suggestion and for contributing to the Flatiron School curriculum! 💙
