### ISSUE TITLE
Missing "and" in '...we want then reassign...'?

### ISSUE THREAD

**Issue by brigj1** [learn-co-curriculum/phase-0-intro-to-js-2-arrays#6]
### Canvas Link

https://learning.flatironschool.com/courses/5185/pages/arrays?module_item_id=396117

### Concern

In "Updating the Value of an Element" we have:
To do that, we access the element we want then reassign that element's value using =.

This part needs rework:
... we want then reassign ...

### Suggested Changes

Maybe add "and" to this:
To do that, we access the element we want then reassign that element's value using =.

to get this:
To do that, we access the element we want and then reassign that element's value using =.

**Comment by lizbur10** [comment]
Thanks @brigj1 ! I've made some edits to clarify it 💙
